import type { ClaimBlueprint } from "./claim-types";

export const claimBlueprints: ClaimBlueprint[] = [
  {
    claimBlueprintId: "wechsel-non-payment",
    instrumentType: "wechsel",
    label: "Nichtzahlung bei Verfall",
    description: "Zahlung am verfalltag nicht erfolgt oder verspätet.",
    compatibleTargetTypes: ["template_field", "settlement_event", "obligation"],
    defaultClaimType: "non_payment",
    defaultCategory: "payment_default",
    suggestedEvidenceTypes: ["payment_proof", "settlement_log", "notice_letter"],
    suggestedRemedies: ["payment_order", "late_fee", "escalation"],
    severity: "critical",
    requiresAmount: true,
    requiresClauseReference: false,
    requiresSettlementReference: true,
    requiresDocumentReference: true
  },
  {
    claimBlueprintId: "wechsel-aval-missing",
    instrumentType: "wechsel",
    label: "Aval fehlt",
    description: "Sicherungspartei fehlt trotz avalVorhanden=true.",
    compatibleTargetTypes: ["template_field", "document_requirement", "obligation"],
    defaultClaimType: "missing_security",
    defaultCategory: "security_breach",
    suggestedEvidenceTypes: ["assignment_document", "signature_page"],
    suggestedRemedies: ["specific_performance", "recourse", "escalation"],
    severity: "critical",
    requiresAmount: false,
    requiresClauseReference: false,
    requiresSettlementReference: false,
    requiresDocumentReference: true
  },
  {
    claimBlueprintId: "schuldschein-partial-payment",
    instrumentType: "schuldschein",
    label: "Teilzahlung statt voller Rate",
    description: "Raten-/Endfaelligkeitszahlung nur teilweise erfolgt.",
    compatibleTargetTypes: ["settlement_event", "template_field", "payment_schedule_entry"],
    defaultClaimType: "partial_payment",
    defaultCategory: "settlement_variance",
    suggestedEvidenceTypes: ["payment_proof", "settlement_log"],
    suggestedRemedies: ["payment_order", "late_fee"],
    severity: "warning",
    requiresAmount: true,
    requiresClauseReference: false,
    requiresSettlementReference: true,
    requiresDocumentReference: false
  },
  {
    claimBlueprintId: "schuldschein-default-interest-dispute",
    instrumentType: "schuldschein",
    label: "Verzugszins streitig",
    description: "Anwendung oder Hoehe von verzugszins wird bestritten.",
    compatibleTargetTypes: ["template_field", "clause_block", "obligation"],
    defaultClaimType: "clause_breach",
    defaultCategory: "clause_dispute",
    suggestedEvidenceTypes: ["contract_extract", "settlement_log"],
    suggestedRemedies: ["declaratory_relief", "interest_adjustment", "escalation"],
    severity: "warning",
    requiresAmount: true,
    requiresClauseReference: true,
    requiresSettlementReference: false,
    requiresDocumentReference: false
  },
  {
    claimBlueprintId: "zession-receivable-validity",
    instrumentType: "zession",
    label: "Bestand der Forderung bestritten",
    description: "GewaehrleistungBestand verletzt oder Falschdarstellung.",
    compatibleTargetTypes: ["template_field", "document_requirement", "uploaded_document"],
    defaultClaimType: "warranty_breach",
    defaultCategory: "warranty_dispute",
    suggestedEvidenceTypes: ["assignment_document", "origin_document", "warranty_schedule"],
    suggestedRemedies: ["recourse", "rescission", "indemnity"],
    severity: "critical",
    requiresAmount: true,
    requiresClauseReference: false,
    requiresSettlementReference: false,
    requiresDocumentReference: true
  },
  {
    claimBlueprintId: "zession-notification-missing",
    instrumentType: "zession",
    label: "Drittschuldner nicht informiert",
    description: "Benachrichtigungspflicht aus offener Zession nicht eingehalten.",
    compatibleTargetTypes: ["template_field", "document_requirement", "obligation"],
    defaultClaimType: "missing_document",
    defaultCategory: "document_non_compliance",
    suggestedEvidenceTypes: ["notice_letter", "assignment_document"],
    suggestedRemedies: ["document_cure", "damages_claim", "escalation"],
    severity: "warning",
    requiresAmount: false,
    requiresClauseReference: false,
    requiresSettlementReference: false,
    requiresDocumentReference: true
  },
  {
    claimBlueprintId: "commenda-reporting-breach",
    instrumentType: "commenda",
    label: "Reportingpflicht verletzt",
    description: "Reporting/ Rechenschaftslegung nicht oder mangelhaft erbracht.",
    compatibleTargetTypes: ["template_field", "clause_block", "document_requirement"],
    defaultClaimType: "reporting_breach",
    defaultCategory: "reporting_breach",
    suggestedEvidenceTypes: ["reporting_statement", "notice_letter", "contract_extract"],
    suggestedRemedies: ["information_order", "penalty", "termination_option"],
    severity: "warning",
    requiresAmount: false,
    requiresClauseReference: true,
    requiresSettlementReference: false,
    requiresDocumentReference: true
  },
  {
    claimBlueprintId: "commenda-profit-share-dispute",
    instrumentType: "commenda",
    label: "Gewinnverteilung bestritten",
    description: "Abweichung zur vereinbarten Gewinnverteilung.",
    compatibleTargetTypes: ["template_field", "clause_block", "settlement_event"],
    defaultClaimType: "settlement_mismatch",
    defaultCategory: "clause_dispute",
    suggestedEvidenceTypes: ["reporting_statement", "settlement_log"],
    suggestedRemedies: ["declaratory_relief", "payment_order", "indemnity"],
    severity: "critical",
    requiresAmount: true,
    requiresClauseReference: true,
    requiresSettlementReference: true,
    requiresDocumentReference: false
  },
  {
    claimBlueprintId: "guelt-annuity-missing",
    instrumentType: "guelt",
    label: "Rentenzahlung ausgeblieben",
    description: "Periodische Rentenzahlung nicht erbracht.",
    compatibleTargetTypes: ["template_field", "settlement_event", "document_requirement"],
    defaultClaimType: "non_payment",
    defaultCategory: "payment_default",
    suggestedEvidenceTypes: ["payment_proof", "settlement_log"],
    suggestedRemedies: ["payment_order", "late_fee", "escalation"],
    severity: "critical",
    requiresAmount: true,
    requiresClauseReference: false,
    requiresSettlementReference: true,
    requiresDocumentReference: true
  },
  {
    claimBlueprintId: "garantie-call-formality",
    instrumentType: "garantie",
    label: "Abrufformalitaeten streitig",
    description: "Inanspruchnahme wird wegen Formfragen bestritten.",
    compatibleTargetTypes: ["template_field", "clause_block", "uploaded_document"],
    defaultClaimType: "clause_breach",
    defaultCategory: "clause_dispute",
    suggestedEvidenceTypes: ["contract_extract", "notice_letter", "signature_page"],
    suggestedRemedies: ["declaratory_relief", "specific_performance"],
    severity: "warning",
    requiresAmount: false,
    requiresClauseReference: true,
    requiresSettlementReference: false,
    requiresDocumentReference: true
  },
  {
    claimBlueprintId: "vorschuss-proof-missing",
    instrumentType: "vorschuss",
    label: "Nachweispflichten nicht erfuellt",
    description: "Unterlagen fuer Forderungsquelle oder Trigger fehlen.",
    compatibleTargetTypes: ["document_requirement", "uploaded_document", "template_field"],
    defaultClaimType: "missing_document",
    defaultCategory: "document_non_compliance",
    suggestedEvidenceTypes: ["origin_document", "payment_proof", "notice_letter"],
    suggestedRemedies: ["document_cure", "suspension", "escalation"],
    severity: "warning",
    requiresAmount: false,
    requiresClauseReference: false,
    requiresSettlementReference: false,
    requiresDocumentReference: true
  }
];

export function getClaimBlueprintsForInstrumentType(instrumentType: ClaimBlueprint["instrumentType"]) {
  return claimBlueprints.filter((blueprint) => blueprint.instrumentType === instrumentType);
}
