import type { ClauseBlock } from "./field-types";

export const baseClauseBlocks: ClauseBlock[] = [
  {
    id: "rechtswahl",
    title: "Rechtswahl",
    category: "legal",
    editable: true,
    defaultSelected: true,
    tags: ["jurisdiction", "law"],
    disputable: true,
    disputeCategories: ["jurisdiction_conflict"],
    standardRemedies: ["clarification", "forum_change_request"],
    defaultEvidenceTypes: ["contract_extract"],
    escalationHints: ["legal_review"],
    text: "Für dieses Instrument gilt das im Feld Rechtswahl benannte materielle Recht. Kollisionsrechtliche Verweisungen werden ausgeschlossen."
  },
  {
    id: "gerichtsstand",
    title: "Gerichtsstand",
    category: "legal",
    editable: true,
    defaultSelected: true,
    tags: ["court", "enforcement"],
    disputable: true,
    disputeCategories: ["forum_dispute"],
    standardRemedies: ["forum_confirmation", "procedural_order"],
    defaultEvidenceTypes: ["jurisdiction_notice"],
    escalationHints: ["court_precheck"],
    text: "Ausschließlicher Gerichtsstand ist der im Instrument benannte Gerichtsstand, soweit gesetzlich zulässig."
  },
  {
    id: "schiedsvereinbarung",
    title: "Schiedsvereinbarung",
    category: "legal",
    editable: true,
    tags: ["arbitration"],
    disputable: true,
    disputeCategories: ["arbitration_scope"],
    standardRemedies: ["arbitration_trigger"],
    defaultEvidenceTypes: ["arbitration_notice"],
    escalationHints: ["arbitration_board"],
    text: "Streitigkeiten werden nach der benannten Schiedsordnung durch ein Schiedsgericht entschieden."
  },
  {
    id: "protestverzicht",
    title: "Protestverzicht",
    category: "historical",
    editable: true,
    historical: true,
    tags: ["wechsel", "historical"],
    disputable: true,
    disputeCategories: ["protest_waiver_dispute"],
    standardRemedies: ["waiver_confirmation", "procedural_reset"],
    defaultEvidenceTypes: ["notice_of_non_payment"],
    escalationHints: ["procedural_review"],
    text: "Der Inhaber verzichtet auf die Protesterhebung, sofern gesetzlich zulässig."
  },
  {
    id: "rueckgriff",
    title: "Rückgriff",
    category: "enforcement",
    editable: true,
    defaultSelected: true,
    tags: ["recourse"],
    disputable: true,
    disputeCategories: ["recourse_dispute"],
    standardRemedies: ["recourse_enforcement", "indemnity"],
    defaultEvidenceTypes: ["demand_letter", "payment_history"],
    escalationHints: ["collections_escalation"],
    text: "Bei Nichtleistung stehen dem Berechtigten die vertraglich und gesetzlich vorgesehenen Rückgriffsrechte gegen Vorverpflichtete zu."
  },
  {
    id: "event_of_default",
    title: "Event of Default",
    category: "enforcement",
    editable: true,
    defaultSelected: true,
    tags: ["default", "termination"],
    disputable: true,
    disputeCategories: ["default_trigger_dispute"],
    standardRemedies: ["acceleration", "payment_order", "collateral_enforcement"],
    defaultEvidenceTypes: ["default_notice", "settlement_log"],
    escalationHints: ["legal_escalation"],
    text: "Ein Event of Default liegt insbesondere bei Zahlungsverzug, unzutreffenden Zusicherungen oder Verletzung wesentlicher Verpflichtungen vor."
  },
  {
    id: "reportingpflicht",
    title: "Reportingpflicht",
    category: "reporting",
    editable: true,
    tags: ["reporting", "commenda"],
    disputable: true,
    disputeCategories: ["reporting_breach"],
    standardRemedies: ["information_order", "penalty", "termination_option"],
    defaultEvidenceTypes: ["reporting_statement", "request_log"],
    escalationHints: ["operator_review"],
    text: "Der operative Partner übermittelt dem Kapitalgeber in den vereinbarten Intervallen vollständige und prüffähige Berichte."
  },
  {
    id: "mahnverfahren",
    title: "Mahnverfahren",
    category: "enforcement",
    editable: true,
    tags: ["payment", "collections"],
    disputable: true,
    disputeCategories: ["dunning_process_dispute"],
    standardRemedies: ["notice_restart", "late_fee_adjustment"],
    defaultEvidenceTypes: ["dunning_notice"],
    escalationHints: ["collections_review"],
    text: "Vor Einleitung streitiger Verfahren erfolgt ein gestuftes Mahnverfahren gemäß Mahnstufenmodell."
  },
  {
    id: "geheimhaltung",
    title: "Geheimhaltung",
    category: "confidentiality",
    editable: true,
    defaultSelected: true,
    tags: ["nda"],
    disputable: true,
    disputeCategories: ["confidentiality_breach"],
    standardRemedies: ["injunction", "damages_claim"],
    defaultEvidenceTypes: ["disclosure_evidence"],
    escalationHints: ["compliance_office"],
    text: "Nicht öffentliche Informationen zu Forderung, Schuldgrund, Sicherheiten und Gegenparteien sind vertraulich zu behandeln."
  },
  {
    id: "uebertragbarkeit",
    title: "Übertragbarkeit",
    category: "legal",
    editable: true,
    defaultSelected: true,
    tags: ["assignment", "marketplace"],
    disputable: true,
    disputeCategories: ["assignment_scope_dispute"],
    standardRemedies: ["assignment_clarification", "consent_repair"],
    defaultEvidenceTypes: ["assignment_document"],
    escalationHints: ["transfer_committee"],
    text: "Die Übertragung erfolgt nach den im Instrument festgelegten Regeln einschließlich Benachrichtigungs- und Zustimmungserfordernissen."
  },
  {
    id: "kuendigung",
    title: "Kündigung",
    category: "enforcement",
    editable: true,
    tags: ["termination"],
    disputable: true,
    disputeCategories: ["termination_right_dispute"],
    standardRemedies: ["termination_confirmation", "cure_period"],
    defaultEvidenceTypes: ["breach_notice"],
    escalationHints: ["legal_review"],
    text: "Bei wesentlicher Pflichtverletzung ist eine außerordentliche Kündigung nach angemessener Nachfrist zulässig."
  },
  {
    id: "vollstreckungsunterwerfung",
    title: "Vollstreckungsunterwerfung",
    category: "enforcement",
    editable: true,
    expertOnly: true,
    tags: ["notarial", "execution"],
    disputable: true,
    disputeCategories: ["enforcement_submission_dispute"],
    standardRemedies: ["notarial_enforcement", "court_confirmation"],
    defaultEvidenceTypes: ["notarial_record"],
    escalationHints: ["enforcement_counsel"],
    text: "Der Verpflichtete unterwirft sich der sofortigen Zwangsvollstreckung aus einer notariellen Urkunde, sofern einschlägig vereinbart."
  },
  {
    id: "historische_formel",
    title: "Historische Formelklausel",
    category: "historical",
    editable: true,
    historical: true,
    tags: ["historical", "formula"],
    disputable: true,
    disputeCategories: ["formula_interpretation_dispute"],
    standardRemedies: ["interpretation_note"],
    defaultEvidenceTypes: ["contract_extract"],
    escalationHints: ["historical_legal_review"],
    text: "Die historische Formulierung bleibt interpretatorisch nachrangig gegenüber den modern strukturierten Vertragsparametern."
  }
];

export function getClauseBlockById(id: string): ClauseBlock | undefined {
  return baseClauseBlocks.find((clause) => clause.id === id);
}
