import type { DashboardDataSet, DashboardInstrument } from "./dashboard-types";

function daysFromNow(days: number): string {
  const date = new Date();
  date.setDate(date.getDate() + days);
  return date.toISOString();
}

const instruments: DashboardInstrument[] = [
  {
    id: "ins-001",
    title: "Wechsel Nordhandel 2026-11",
    type: "wechsel",
    counterparty: "Nordhandel AG",
    nominalVolume: 125000,
    currency: "CHF",
    maturityDate: daysFromNow(5),
    status: "active",
    riskLevel: "warning",
    riskScore: 63,
    lastActivityAt: daysFromNow(-1),
    owner: "Iris Issuer",
    isMine: true,
    publishedOffer: true,
    settlementPrepared: false,
    settlementMethod: "bank_transfer",
    requiredDocumentCount: 6,
    uploadedDocumentCount: 5,
    missingSignatureCount: 1,
    marketplaceViews: 142,
    watchlistCount: 22,
    inquiryCount: 5,
    discountPercent: 4.2,
    manualReviewFlag: false,
    counterpartyComplete: true
  },
  {
    id: "ins-002",
    title: "Schuldschein Maschinenpark A",
    type: "schuldschein",
    counterparty: "Keller Maschinenbau",
    nominalVolume: 480000,
    currency: "EUR",
    maturityDate: daysFromNow(21),
    status: "published",
    riskLevel: "info",
    riskScore: 41,
    lastActivityAt: daysFromNow(-2),
    owner: "Iris Issuer",
    isMine: true,
    publishedOffer: true,
    settlementPrepared: true,
    settlementMethod: "escrow",
    requiredDocumentCount: 8,
    uploadedDocumentCount: 8,
    missingSignatureCount: 0,
    marketplaceViews: 309,
    watchlistCount: 61,
    inquiryCount: 17,
    discountPercent: 3.1,
    manualReviewFlag: false,
    counterpartyComplete: true
  },
  {
    id: "ins-003",
    title: "Guelt Bern-Land Rang 1",
    type: "guelt",
    counterparty: "Estate Holder Bern Sued",
    nominalVolume: 900000,
    currency: "CHF",
    maturityDate: daysFromNow(61),
    status: "in_review",
    riskLevel: "warning",
    riskScore: 68,
    lastActivityAt: daysFromNow(-4),
    owner: "Olaf Operator",
    isMine: false,
    publishedOffer: false,
    settlementPrepared: true,
    settlementMethod: "custody_release",
    requiredDocumentCount: 10,
    uploadedDocumentCount: 7,
    missingSignatureCount: 2,
    marketplaceViews: 81,
    watchlistCount: 8,
    inquiryCount: 2,
    discountPercent: 6.4,
    manualReviewFlag: true,
    counterpartyComplete: true
  },
  {
    id: "ins-004",
    title: "Commenda Spice Route 2026",
    type: "commenda",
    counterparty: "Olaf Operator",
    nominalVolume: 800000,
    currency: "USD",
    maturityDate: daysFromNow(33),
    status: "in_negotiation",
    riskLevel: "warning",
    riskScore: 71,
    lastActivityAt: daysFromNow(-1),
    owner: "Ines Investor",
    isMine: false,
    publishedOffer: false,
    settlementPrepared: false,
    settlementMethod: "escrow",
    requiredDocumentCount: 9,
    uploadedDocumentCount: 6,
    missingSignatureCount: 1,
    marketplaceViews: 210,
    watchlistCount: 37,
    inquiryCount: 9,
    discountPercent: 8.8,
    manualReviewFlag: true,
    counterpartyComplete: false
  },
  {
    id: "ins-005",
    title: "Zession Pool Q3 Retail",
    type: "zession",
    counterparty: "Retail Group Central",
    nominalVolume: 350000,
    currency: "CHF",
    maturityDate: daysFromNow(-3),
    status: "overdue",
    riskLevel: "critical",
    riskScore: 84,
    lastActivityAt: daysFromNow(-2),
    owner: "Iris Issuer",
    isMine: true,
    publishedOffer: true,
    settlementPrepared: false,
    settlementMethod: "bank_transfer",
    requiredDocumentCount: 7,
    uploadedDocumentCount: 4,
    missingSignatureCount: 1,
    marketplaceViews: 268,
    watchlistCount: 39,
    inquiryCount: 12,
    discountPercent: 5.4,
    manualReviewFlag: true,
    counterpartyComplete: false
  },
  {
    id: "ins-006",
    title: "Garantie Export Linie A",
    type: "garantie",
    counterparty: "Helvetic Trade GmbH",
    nominalVolume: 220000,
    currency: "EUR",
    maturityDate: daysFromNow(9),
    status: "pending_settlement",
    riskLevel: "warning",
    riskScore: 64,
    lastActivityAt: daysFromNow(-3),
    owner: "Gavin Guarantor",
    isMine: false,
    publishedOffer: false,
    settlementPrepared: false,
    settlementMethod: "bank_transfer",
    requiredDocumentCount: 5,
    uploadedDocumentCount: 5,
    missingSignatureCount: 0,
    marketplaceViews: 56,
    watchlistCount: 4,
    inquiryCount: 1,
    discountPercent: 2.1,
    manualReviewFlag: false,
    counterpartyComplete: true
  },
  {
    id: "ins-007",
    title: "Vorschuss ERP Lizenzflow",
    type: "vorschuss",
    counterparty: "CloudBits AG",
    nominalVolume: 175000,
    currency: "CHF",
    maturityDate: daysFromNow(2),
    status: "active",
    riskLevel: "warning",
    riskScore: 67,
    lastActivityAt: daysFromNow(-1),
    owner: "Iris Issuer",
    isMine: true,
    publishedOffer: true,
    settlementPrepared: false,
    settlementMethod: "escrow",
    requiredDocumentCount: 6,
    uploadedDocumentCount: 6,
    missingSignatureCount: 0,
    marketplaceViews: 118,
    watchlistCount: 16,
    inquiryCount: 3,
    discountPercent: 4.8,
    manualReviewFlag: false,
    counterpartyComplete: true
  },
  {
    id: "ins-008",
    title: "Eigenwechsel Logistik Linie C",
    type: "solawechsel",
    counterparty: "RapidMove SA",
    nominalVolume: 98000,
    currency: "CHF",
    maturityDate: daysFromNow(15),
    status: "draft",
    riskLevel: "info",
    riskScore: 39,
    lastActivityAt: daysFromNow(-5),
    owner: "Iris Issuer",
    isMine: true,
    publishedOffer: false,
    settlementPrepared: false,
    settlementMethod: "bank_transfer",
    requiredDocumentCount: 4,
    uploadedDocumentCount: 2,
    missingSignatureCount: 2,
    marketplaceViews: 0,
    watchlistCount: 0,
    inquiryCount: 0,
    discountPercent: 0,
    manualReviewFlag: false,
    counterpartyComplete: true
  },
  {
    id: "ins-009",
    title: "Schuldschein Energiepark Delta",
    type: "schuldschein",
    counterparty: "Solaris Infra AG",
    nominalVolume: 690000,
    currency: "EUR",
    maturityDate: daysFromNow(44),
    status: "active",
    riskLevel: "critical",
    riskScore: 89,
    lastActivityAt: daysFromNow(-2),
    owner: "Olaf Operator",
    isMine: false,
    publishedOffer: true,
    settlementPrepared: true,
    settlementMethod: "escrow",
    requiredDocumentCount: 10,
    uploadedDocumentCount: 9,
    missingSignatureCount: 0,
    marketplaceViews: 360,
    watchlistCount: 88,
    inquiryCount: 25,
    discountPercent: 9.3,
    manualReviewFlag: true,
    counterpartyComplete: false
  },
  {
    id: "ins-010",
    title: "Zession SaaS Forderungen DACH",
    type: "zession",
    counterparty: "B2B Software Hub",
    nominalVolume: 265000,
    currency: "EUR",
    maturityDate: daysFromNow(7),
    status: "published",
    riskLevel: "warning",
    riskScore: 61,
    lastActivityAt: daysFromNow(-1),
    owner: "Iris Issuer",
    isMine: true,
    publishedOffer: true,
    settlementPrepared: true,
    settlementMethod: "bank_transfer",
    requiredDocumentCount: 6,
    uploadedDocumentCount: 6,
    missingSignatureCount: 0,
    marketplaceViews: 204,
    watchlistCount: 19,
    inquiryCount: 6,
    discountPercent: 5.9,
    manualReviewFlag: false,
    counterpartyComplete: true
  },
  {
    id: "ins-011",
    title: "Guelt Alpine Lodge Income Right",
    type: "guelt",
    counterparty: "Alpine Lodge Group",
    nominalVolume: 510000,
    currency: "CHF",
    maturityDate: daysFromNow(95),
    status: "resolved",
    riskLevel: "info",
    riskScore: 34,
    lastActivityAt: daysFromNow(-8),
    owner: "Olaf Operator",
    isMine: false,
    publishedOffer: false,
    settlementPrepared: true,
    settlementMethod: "custody_release",
    requiredDocumentCount: 8,
    uploadedDocumentCount: 8,
    missingSignatureCount: 0,
    marketplaceViews: 34,
    watchlistCount: 2,
    inquiryCount: 0,
    discountPercent: 0,
    manualReviewFlag: false,
    counterpartyComplete: true
  },
  {
    id: "ins-012",
    title: "Commenda Port Trade II",
    type: "commenda",
    counterparty: "Oceanic Operator Ltd",
    nominalVolume: 1040000,
    currency: "USD",
    maturityDate: daysFromNow(18),
    status: "in_dispute",
    riskLevel: "critical",
    riskScore: 92,
    lastActivityAt: daysFromNow(-1),
    owner: "Ines Investor",
    isMine: false,
    publishedOffer: false,
    settlementPrepared: false,
    settlementMethod: "escrow",
    requiredDocumentCount: 11,
    uploadedDocumentCount: 7,
    missingSignatureCount: 2,
    marketplaceViews: 174,
    watchlistCount: 27,
    inquiryCount: 11,
    discountPercent: 10.2,
    manualReviewFlag: true,
    counterpartyComplete: false
  },
  {
    id: "ins-013",
    title: "Vorschuss Creator Economy Bundle",
    type: "vorschuss",
    counterparty: "CreatorHub SA",
    nominalVolume: 132000,
    currency: "EUR",
    maturityDate: daysFromNow(1),
    status: "pending_settlement",
    riskLevel: "warning",
    riskScore: 58,
    lastActivityAt: daysFromNow(0),
    owner: "Iris Issuer",
    isMine: true,
    publishedOffer: true,
    settlementPrepared: false,
    settlementMethod: "bank_transfer",
    requiredDocumentCount: 5,
    uploadedDocumentCount: 4,
    missingSignatureCount: 1,
    marketplaceViews: 88,
    watchlistCount: 13,
    inquiryCount: 4,
    discountPercent: 4.4,
    manualReviewFlag: false,
    counterpartyComplete: true
  },
  {
    id: "ins-014",
    title: "Garantie Construction Lot B",
    type: "garantie",
    counterparty: "BuildCore GmbH",
    nominalVolume: 305000,
    currency: "CHF",
    maturityDate: daysFromNow(-8),
    status: "archived",
    riskLevel: "info",
    riskScore: 22,
    lastActivityAt: daysFromNow(-12),
    owner: "Gavin Guarantor",
    isMine: false,
    publishedOffer: false,
    settlementPrepared: true,
    settlementMethod: "bank_transfer",
    requiredDocumentCount: 6,
    uploadedDocumentCount: 6,
    missingSignatureCount: 0,
    marketplaceViews: 14,
    watchlistCount: 1,
    inquiryCount: 0,
    discountPercent: 0,
    manualReviewFlag: false,
    counterpartyComplete: true
  },
  {
    id: "ins-015",
    title: "Wechsel MedTech Receivable 7",
    type: "wechsel",
    counterparty: "MedNova AG",
    nominalVolume: 410000,
    currency: "EUR",
    maturityDate: daysFromNow(6),
    status: "published",
    riskLevel: "warning",
    riskScore: 69,
    lastActivityAt: daysFromNow(-1),
    owner: "Iris Issuer",
    isMine: true,
    publishedOffer: true,
    settlementPrepared: true,
    settlementMethod: "escrow",
    requiredDocumentCount: 7,
    uploadedDocumentCount: 7,
    missingSignatureCount: 0,
    marketplaceViews: 297,
    watchlistCount: 58,
    inquiryCount: 19,
    discountPercent: 6.1,
    manualReviewFlag: false,
    counterpartyComplete: true
  }
];

export const dashboardMockData: DashboardDataSet = {
  instruments,
  activities: [
    {
      id: "act-001",
      timestamp: daysFromNow(-1),
      actor: "Iris Issuer",
      action: "instrument_created",
      entityType: "instrument",
      entityTitle: "Vorschuss Creator Economy Bundle"
    },
    {
      id: "act-002",
      timestamp: daysFromNow(-1),
      actor: "Olaf Operator",
      action: "clause_updated",
      entityType: "clause",
      entityTitle: "Commenda Port Trade II",
      severity: "warning"
    },
    {
      id: "act-003",
      timestamp: daysFromNow(-1),
      actor: "Gavin Guarantor",
      action: "document_uploaded",
      entityType: "document",
      entityTitle: "Garantie Export Linie A"
    },
    {
      id: "act-004",
      timestamp: daysFromNow(-2),
      actor: "Ines Investor",
      action: "listing_published",
      entityType: "listing",
      entityTitle: "Schuldschein Maschinenpark A"
    },
    {
      id: "act-005",
      timestamp: daysFromNow(-2),
      actor: "Dispute Desk",
      action: "dispute_opened",
      entityType: "dispute",
      entityTitle: "Commenda Port Trade II",
      severity: "critical"
    },
    {
      id: "act-006",
      timestamp: daysFromNow(-3),
      actor: "Compliance",
      action: "counterparty_validated",
      entityType: "counterparty",
      entityTitle: "Nordhandel AG"
    },
    {
      id: "act-007",
      timestamp: daysFromNow(-4),
      actor: "Settlement Ops",
      action: "settlement_confirmed",
      entityType: "settlement",
      entityTitle: "Zession SaaS Forderungen DACH"
    },
    {
      id: "act-008",
      timestamp: daysFromNow(-5),
      actor: "Iris Issuer",
      action: "listing_published",
      entityType: "listing",
      entityTitle: "Wechsel MedTech Receivable 7"
    }
  ],
  settlements: [
    {
      id: "set-001",
      instrumentId: "ins-001",
      instrumentTitle: "Wechsel Nordhandel 2026-11",
      method: "bank_transfer",
      dueDate: daysFromNow(5),
      amount: 125000,
      currency: "CHF",
      status: "pending",
      paymentEvidenceUploaded: false,
      nextAction: "Payment instruction + evidence upload"
    },
    {
      id: "set-002",
      instrumentId: "ins-013",
      instrumentTitle: "Vorschuss Creator Economy Bundle",
      method: "bank_transfer",
      dueDate: daysFromNow(1),
      amount: 132000,
      currency: "EUR",
      status: "partial",
      paymentEvidenceUploaded: false,
      nextAction: "Confirm partial payment + collect receipt"
    },
    {
      id: "set-003",
      instrumentId: "ins-010",
      instrumentTitle: "Zession SaaS Forderungen DACH",
      method: "bank_transfer",
      dueDate: daysFromNow(7),
      amount: 265000,
      currency: "EUR",
      status: "confirmed",
      paymentEvidenceUploaded: true,
      nextAction: "Archive settlement package"
    },
    {
      id: "set-004",
      instrumentId: "ins-006",
      instrumentTitle: "Garantie Export Linie A",
      method: "escrow",
      dueDate: daysFromNow(9),
      amount: 220000,
      currency: "EUR",
      status: "pending",
      paymentEvidenceUploaded: false,
      nextAction: "Prepare escrow release memo"
    }
  ],
  disputes: [
    {
      id: "dis-001",
      instrumentId: "ins-012",
      instrumentTitle: "Commenda Port Trade II",
      status: "mediation",
      escalationStage: "stage_2",
      responseDueAt: daysFromNow(2),
      amountInDispute: 300000,
      currency: "USD",
      documentationStatus: "partial",
      counterparty: "Oceanic Operator Ltd",
      owner: "Dispute Team A"
    },
    {
      id: "dis-002",
      instrumentId: "ins-005",
      instrumentTitle: "Zession Pool Q3 Retail",
      status: "open",
      escalationStage: "stage_1",
      responseDueAt: daysFromNow(1),
      amountInDispute: 85000,
      currency: "CHF",
      documentationStatus: "missing",
      counterparty: "Retail Group Central",
      owner: "Legal Ops"
    },
    {
      id: "dis-003",
      instrumentId: "ins-009",
      instrumentTitle: "Schuldschein Energiepark Delta",
      status: "under_review",
      escalationStage: "stage_1",
      responseDueAt: daysFromNow(6),
      amountInDispute: 120000,
      currency: "EUR",
      documentationStatus: "complete",
      counterparty: "Solaris Infra AG",
      owner: "Dispute Team B"
    }
  ],
  quickActions: [
    {
      id: "qa-001",
      label: "Neues Instrument erstellen",
      description: "Instrument wizard starten",
      href: "/instruments/new"
    },
    {
      id: "qa-002",
      label: "Entwurf fortsetzen",
      description: "Offene Drafts bearbeiten",
      href: "/instruments?filter=draft"
    },
    {
      id: "qa-003",
      label: "Angebot veroeffentlichen",
      description: "Draft nach Marketplace pushen",
      href: "/marketplace",
      severity: "info"
    },
    {
      id: "qa-004",
      label: "Dokument hochladen",
      description: "Missing docs reduzieren",
      href: "/dashboard?tab=risk",
      severity: "warning"
    },
    {
      id: "qa-005",
      label: "Settlement vorbereiten",
      description: "Pending settlements abarbeiten",
      href: "/dashboard?tab=settlement",
      severity: "warning"
    },
    {
      id: "qa-006",
      label: "Dispute eroeffnen",
      description: "Neue Streitfaelle dokumentieren",
      href: "/disputes",
      severity: "critical"
    },
    {
      id: "qa-007",
      label: "Gegenpartei pruefen",
      description: "KYC/Counterparty completeness",
      href: "/dashboard?tab=risk"
    }
  ]
};
